---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    testing:
      hosts:
        webserver_testing:
          ansible_host: 192.168.1.100

    production:
      hosts:
        webserver_production:
          ansible_host: 144.91.85.65

    ci:
      hosts:
        webserver_ci:
          ansible_host: 192.168.1.97
